#!/bin/sh
# Builds the Rust core for the app, from ../core:
#   Frameworks/AgentzFFI.xcframework          the static library and its C header
#   Sources/AgentzCore/Generated/*.swift      its Swift side, generated by UniFFI
# Both are build output; `swift build` needs them, so the Makefile runs this
# first.
set -eu

dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# The bindgen tool finds uniffi.toml through `cargo metadata`, which looks
# in the current folder.
cd "$dir/../core"
cargo build -p agentz-core --release
target=$(cargo metadata --format-version 1 --no-deps |
    sed -n 's/.*"target_directory":"\([^"]*\)".*/\1/p')
lib="$target/release/libagentz_core.a"

gen="$dir/.build/agentz-core"
rm -rf "$gen"
mkdir -p "$gen/include" "$gen/swift"
bindgen() {
    cargo run -q -p uniffi-bindgen-swift -- "$lib" "$@"
}
bindgen "$gen/include" --headers --modulemap --module-name AgentzFFI --modulemap-filename module.modulemap
bindgen "$gen/swift" --swift-sources

# Replace the Swift file only when it changed, so Swift does not recompile.
mkdir -p "$dir/Sources/AgentzCore/Generated"
for f in "$gen/swift"/*.swift; do
    out="$dir/Sources/AgentzCore/Generated/$(basename "$f")"
    cmp -s "$f" "$out" || cp "$f" "$out"
done

rm -rf "$dir/Frameworks/AgentzFFI.xcframework"
mkdir -p "$dir/Frameworks"
xcodebuild -create-xcframework -library "$lib" -headers "$gen/include" \
    -output "$dir/Frameworks/AgentzFFI.xcframework" >/dev/null
